
name: Python CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.11]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -e .
      - name: Set dummy OpenAI API key
        run: echo "OPENAI_API_KEY=dummy" >> $GITHUB_ENV
      - name: Run tests
        run: |
          pytest

  style:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11
      - name: Install formatting tools
        run: |
          pip install black isort
      - name: Check formatting with Black
        run: |
          black --check .
      - name: Check import order with isort
        run: |
          isort --check-only .